services:
  awg-server:
    build:
      context: .
      dockerfile: Dockerfile-awg-server
    container_name: awg-server
    ports:
      - "${PORT}:${PORT}"
      - "${AWG_PORT}:${AWG_PORT}/udp"
    environment:
      - PORT=${PORT}
      - AWG_PORT=${AWG_PORT}
      - CONFIG=/data/config.json
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - amneziawg-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile-telegram-bot
    container_name: tg-bot
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - SQLITE_FILENAME=${SQLITE_FILENAME}
      - OUTLINE_NEW_KEY_METHOD=${OUTLINE_NEW_KEY_METHOD}

networks:
  amneziawg-network:
    driver: bridge
