FROM node:23

# Copy package.json first for better Docker layer caching
COPY package.json ./

# Install Node.js dependencies
RUN npm install
# Copy application files
COPY . .

# Default command
CMD ["npm", "run", "tgbot:start"]
