services:
  amneziawg-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amneziawg-api
    ports:
      - "3444:3444"
      - "51000:51000/udp"
    environment:
      - PORT=3444
      - AWG_PORT=51000
      - CONFIG=/data/config.json
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    volumes:
      - ./data:/data
    restart: unless-stopped
    networks:
      - amneziawg-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  amneziawg-network:
    driver: bridge
